apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: l95o3y2sw-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: l95o3y2sw-nodejs 
  name: l95o3y2sw-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: l95o3y2sw-nodejs 
